### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__caffe)

### ISSUE THREAD

**Issue by ghazni123** [DengPingFan/DAVSOD#18]
Hi 

Thank you for your work. I came across this repo and trying to build/run and succeeded to following point but failed at final step:

My development environment is conda and followed the steps on home page of repo.

$$$$python SSAV_test.py 
Traceback (most recent call last):
  File "SSAV_test.py", line 6, in <module>
    import caffe
  File "./mycaffe-convlstm/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "./mycaffe-convlstm/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dynamic module does not define module export function (PyInit__caffe)

Usually this is solved by setting PYTHONPATH but not working here. I have tried following:

1: setting "export PYTHONPATH=.../DAVSOD:$PYTHONPATH"
2: setting "export PYTHONPATH=.../DAVSOD/mycaffe-convlstm/python:$PYTHONPATH"

Could you please advise what is possible cause for this error?

Thanks.

**Comment by ghazni123** [comment]
it was to do with python2 vs python3 - resolved now.
